name: RPU-DisableInteractions
version: '${project.version}'
main: me.fami6xx.famidisableinteractions.Fami_DisableInteractions
api-version: '1.14'
dependency: [RPUniverse]
commands:
  disableinteractions:
    description: Opens the disable interactions menu
    usage: /disableinteractions
    permission: disableinteractions.manage
    aliases:
      - di
      - disable
  dibypass:
    description: Toggles bypass mode for disabled interactions
    usage: /dibypass
    permission: disableinteractions.bypass
    aliases:
      - dib
      - disableinteractionsbypass
permissions:
  disableinteractions.override:
    description: Allows overriding disabled interactions
    default: false
  disableinteractions.manage:
    description: Allows managing disabled interactions
    default: op
  disableinteractions.bypass:
    description: Allows toggling bypass mode
    default: op
